---
- name: Converge
  hosts: all
  roles:
    - role: powo.archive
      par_archive_destination_folder: "/tmp"
      par_archive_extraction_folder: "/tmp/eclipse"
      par_archive_url: copy:{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}/eclipse-fake.tar.gz
      par_archive_checksum: sha256:7713da412ea410370c1fd67e6589b2de792634aeea8f12f1d961d549e261438d
      par_archive_strip: 1
