---
- name: Converge
  hosts: all
  roles:
    - role: powo.archive
      par_archive_destination_folder: "/tmp"
      par_archive_extraction_folder: "/tmp/eclipse"
      par_archive_url: http//ftp.heanet.ie/mirrors/eclipse/technology/epp/downloads/release/oxygen/R/eclipse-java-oxygen-R-linux-gtk-x86_64.tar.gz
      par_archive_checksum: sha1:539e2edd7fe72653a7076e696ade52c4a3bafd0d
      par_archive_strip: 1
